// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {ff6library} from '../models';

export function GetClientStatus():Promise<any>;

export function GetCurrentEncounter():Promise<Array<ff6library.FlattenedEnemy>>;

export function Start():Promise<void>;

export function Stop():Promise<void>;
