// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetClientStatus() {
  return window['go']['ff6library']['Library']['GetClientStatus']();
}

export function GetCurrentEncounter() {
  return window['go']['ff6library']['Library']['GetCurrentEncounter']();
}

export function Start() {
  return window['go']['ff6library']['Library']['Start']();
}

export function Stop() {
  return window['go']['ff6library']['Library']['Stop']();
}
