// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {reference} from '../models';

export function GetClientStatus():Promise<any>;

export function GetCurrentEncounter():Promise<reference.FlattenedEncounter>;

export function Start():Promise<void>;

export function Stop():Promise<void>;
